### ISSUE TITLE
Installation fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by redjohn** [mysqludf/lib_mysqludf_preg#19]
I'm trying to install this on Ubuntu 14.04 and keep getting the message `WARNING: 'aclocal-1.13' is missing on your system.` It looks like I have 1.14 installed, and there are no available packages to install 1.13. Any ideas?

**Comment by gadamo** [comment]
Possible workaround:

It is looking for an `'aclocal-1.13'` binary within the path. Since 1.14 is in place, I would try fooling it with a temporary symlink (e.g. `ln -s /usr/bin/aclocal-1.14 /usr/bin/aclocal-1.13`). 

If you reach successful configuration this way, you can (and should) remove the symlink (`rm  /usr/bin/aclocal-1.13`).

**Comment by redjohn** [comment]
Good idea, this helped. It didn't work right away, but it was easy enough to figure out where to go from here.

**Comment by nitantsoni** [comment]
I was also facing this issue. This is how I fixed it. I think the problem is related to running ./configure without sudo. The EASIEST solution then is to delete all the old files and start over like so:

wget  https://github.com/mysqludf/lib_mysqludf_preg/archive/testing.zip
unzip testing.zip 
cd lib_mysqludf_preg-testing/
sudo ./configure 
sudo make install
sudo make MYSQL="mysql -p" installdb
sudo make test
cd ..
sudo rm -r lib_mysqludf_preg-testing/
sudo rm -r testing.zip 
exit

**Comment by richwaters** [comment]
I'm still not sure what causes this, but it can be corrected by running "aclocal; automake;" from the same directory 'configure' is run in.

**Comment by mabushey** [comment]
No, running "aclocal; automake;" does not fix anything:

root@dev:~/source/lib_mysqludf_preg# ./configure
...
configure: creating ./config.status
config.status: creating Makefile
config.status: creating test/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands

root@dev:~/source/lib_mysqludf_preg# aclocal; automake;
configure.ac:17: error: required file 'config/compile' not found
configure.ac:17:   'automake --add-missing' can install 'compile'
test/Makefile.am:13: warning: wildcard *.test: non-POSIX variable name
test/Makefile.am:13: (probably a GNU make extension)
test/Makefile.am:22: warning: '%'-style pattern rules are a GNU make extension
test/Makefile.am:25: warning: '%'-style pattern rules are a GNU make extension

root@dev:~/source/lib_mysqludf_preg# make install
 cd . && /bin/bash /root/source/lib_mysqludf_preg/config/missing automake-1.13 --foreign
/root/source/lib_mysqludf_preg/config/missing: line 81: automake-1.13: command not found
WARNING: 'automake-1.13' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         http://www.gnu.org/software/automake
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         http://www.gnu.org/software/autoconf
         http://www.gnu.org/software/m4/
         http://www.perl.org/
Makefile:424: recipe for target 'Makefile.in' failed
make: **\* [Makefile.in] Error 1

**Comment by mabushey** [comment]
This gets things further along:

ln -s /usr/bin/automake-1.14 /usr/bin/automake-1.13

root@dev:~/source/lib_mysqludf_preg# make install
 cd . && /bin/bash /root/source/lib_mysqludf_preg/config/missing automake-1.13 --foreign
configure.ac:17: error: required file 'config/compile' not found
configure.ac:17:   'automake --add-missing' can install 'compile'
Makefile:424: recipe for target 'Makefile.in' failed
make: **\* [Makefile.in] Error 1

root@dev:~/source/lib_mysqludf_preg# automake --add-missing
configure.ac:17: installing 'config/compile'
...

root@dev:~/source/lib_mysqludf_preg# make install
...
Libraries have been installed in:
   /usr/lib/mysql/plugin
...

**Comment by proditis** [comment]
The following procedure seemed to solve the problem for me

```
sudo apt-get install libtool automake autoconf autogen # not quite sure about the last one
cd lib_mysqludf_preg
aclocal
automake --add-missing
./configure 
make
```

**Comment by CMCDragonkai** [comment]
@proditis Thanks it worked.

This was the entire procedure (after first installing MySQL):

``` sh
sudo apt-get install libmysqlclient-dev libpcre3-dev
sudo apt-get install libtool automake autoconf autogen
sudo git clone https://github.com/mysqludf/lib_mysqludf_preg.git
cd lib_mysqludf_preg
sudo aclocal
sudo automake --add-missing
sudo ./configure 
sudo make
sudo make install
sudo make MYSQL="mysql -p" installdb
sudo make test
```

**Comment by proditis** [comment]
@CMCDragonkai glad it worked out for you. 

Out of curiosity, why did you perform all the commands with `sudo`? Do you get errors when you run the commands without it? I would expect the only command needing `sudo` to be `make install`. It would be great if you could confirm this.

**Comment by CMCDragonkai** [comment]
I have some complicated permissions. So I couldn't be bothered figuring out the minimum, and just sudoed everything.

**Comment by proditis** [comment]
great, thanks a lot. I'm making a docs/INSTALL.debian with all those details from the issues to contribute to the project and wanted to make sure the steps are ok.

**Comment by mabushey** [comment]
On Debian testing, It appears that if libpcre3 is installed, but not pcre, then the .so links to libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f1c479f2000)

However if the package 'pcre' is installed, then the .so links to libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x00007ff9b4a17000).

Is libpcre.so.1 really preferable to libpcre.so.3?

**Comment by reklatsmasters** [comment]
Use this answer: http://stackoverflow.com/a/3205400/1556249

**Comment by jogaco** [comment]
I'm getting an error

```
ERROR 1125 (HY000) at line 3: Function 'lib_mysqludf_preg_info' already exists
make: *** [installdb] Error 1
```

after `sudo make MYSQL="mysql -p" installdb`

Any clue?

**Comment by jogaco** [comment]
This one did the trick only partially as `sudo make test` still fails but `SELECT PREG_REPLACE();` works fine

https://github.com/mysqludf/lib_mysqludf_preg/pull/16

**Comment by jogaco** [comment]
Here is what worked fine for me. A `service mysql restart` is necessary.

```
sudo apt-get install libmysqlclient-dev libpcre3-dev
sudo apt-get install libtool automake autoconf autogen
sudo git clone https://github.com/mysqludf/lib_mysqludf_preg.git
cd lib_mysqludf_preg
sudo aclocal
sudo automake --add-missing
sudo ./configure 
sudo make
sudo make install
sudo service mysql restart
sudo make MYSQL="mysql -pfoo" installdb
sudo make test
```

**Comment by loureirorg** [comment]
I can confirm that the above (jogaco, proditis, ...) works on Ubuntu 15.10 (and it should be installed as root).

On a Gentoo dist (Apr 2016) I had to run an `autoreconf` command.

```
sudo autoreconf --force --install
sudo ./configure
sudo make
...
```
